joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.10
    autorepeat_rate: 20.0

teleop_twist_joy_node:
  ros__parameters:
    # 왼쪽 스틱: 축0=좌우(회전), 축1=상하(전진)
    axis_linear:
      x: 1
    scale_linear:
      x: 0.20
    scale_linear_turbo:
      x: 0.22

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: -1.0
    scale_angular_turbo:
      yaw: -1.5

    # 버튼 없이 스틱만으로 바로 이동
    require_enable_button: false
    enable_turbo_button: 5    # RB 누르면 터보
